name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        # redis-version: [6, 7]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # # --- Start Redis ---
      # - name: Start Redis
      #   uses: supercharge/redis-github-action@1.7.0
      #   with:
      #     redis-version: ${{ matrix.redis-version }}

      # # --- Install SQLite Development Package ---
      # - name: Install SQLite
      #   run: sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Run linters
        run: |
          black --check .
          flake8 .

      # - name: Run tests
      #   env:
      #     SECRET_KEY: ${{ secrets.SECRET_KEY }}
      #     DATABASE_URL: sqlite:///:memory:
      #     REDIS_URL: redis://localhost:6379
      #     JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      #     STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
      #     REPLICATE_API_KEY: ${{ secrets.REPLICATE_API_KEY }}
      #     STABILITY_API_HOST: ${{ secrets.STABILITY_API_HOST }}
      #     ELEVEN_LABS_VOICE_ID: ${{ secrets.ELEVEN_LABS_VOICE_ID }}
      #     ELEVEN_LABS_API_KEY: ${{ secrets.ELEVEN_LABS_API_KEY }}
      #   run: |
      #     coverage run -m unittest discover tests
      #     coverage xml

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4.0.1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage.xml
